### ISSUE TITLE
Issue with "validated_consent" claim

### ISSUE THREAD

**Issue by pjohnson-hel** [oktadev/okta-smartfhir-demo#33]
Really nice work on this, it is very much appreciated.

I'm currently running through a setup of this process and attempting to test it with Inferno but I'm hitting a snag where a 400 response is being returned. It looks like the culprit is [here](https://github.com/oktadev/okta-smartfhir-demo/blob/46dff7c720f3c40f26959b0771067f44365729ee/lib/token.js#L45).

The question I have is, where does the "validated_consent" claim come from? I didn't find it in the docs, reference guide, or the code itself anywhere except in the link I shared above for token.js. Any information would be very helpful.

Edit: should mention that I am able to workaround this by hard-coding a claim called "valid_consent" into my Okta auth server. That passes the if-check in the code mentioned above. However, I was hoping for more info on how that should actually be handled properly, as it doesn't seem this workaround is correct. Thanks!

**Comment by dancinnamon-okta** [comment]
Hi!
The "valid_consent" claim is actually injected into the token by the token hook (Okta's supported way of customizing tokens).  Here is where that is happening: [Here](https://github.com/oktadev/okta-smartfhir-demo/blob/46dff7c720f3c40f26959b0771067f44365729ee/lib/token_hook.js#L75).

The goal of the token hook is to apply the user's consent decisions that occur on the patient picker. The valid_consent claim is checked because we want to be sure that a user didn't somehow bypass that process.

If that claim is missing- that likely means that your token hook is not executing.  The configuration for that is found in the "access policy" of the authorization server.  To determine what is going on you might take a close look at the authorization policy that will apply to the SMART clients and make sure that you tell it to invoke the token hook [Access Policies](https://github.com/oktadev/okta-smartfhir-docs/blob/main/SETUP.md#access-policies)

(This is the image that shows the policy you need to confirm): https://github.com/oktadev/okta-smartfhir-docs/blob/main/images/access_policy_sample.png
